### ISSUE TITLE
Steps to Reproduce

### ISSUE THREAD

**Issue by wondergo2017** [mr-eggplant/adaxpert0#1]
Great work! I'm really interested in your work.  How to reproduce Table 1 & 2 by your code? Could you provide step-by-step commands?  That'd be of great help. Thanks!

**Comment by mr-eggplant** [comment]
Thank you for your interest!

**Comment by mr-eggplant** [comment]
Thank you for your interest！
To reproduce Tables 1 and 2, you need to run train_spos_supernet.py and train_mb_spos.py alternatively.
For example (in Table 2), first train a supernet on ImageNet-20 by (STEP-1):
```
CUDA_VISIBLE_DEVICES=0,1 horovodrun -np 2 -H localhost:2 python3 adaxpert/train_spos_supernet.py --dataset_class_num 20 
```
and then run the search code based on the trained supernet (STEP-2):
```
python3 adaxpert/train_mb_spos.py --dataset_class_num 20 --supernet_path "/path/to/trained-supernet"
```
Once this step is finished, you can obtain an architecture on the ImageNet-20.

To further obtain an architecture on ImageNet-40, just go to STEP-1 again.
